### ISSUE TITLE
 kaldi::KaldiFatalErrorerror getting feature dimension

### ISSUE THREAD

**Issue by KiAlexander** [veenveenveen/ASR_Kaldi_DNN_Chinese#3]
**when I try run the following commands:**
~/kaldi/egs/ASR_Kaldi_DNN_Chinese$ steps/train_mono.sh --nj 15 data/train data/lang_bigram exp_FG/mono

**I encouter some problem like this:**
steps/train_mono.sh --nj 15 data/train data/lang_bigram exp_FG/mono
steps/train_mono.sh: Initializing monophone system.
feat-to-dim 'ark,s,cs:apply-cmvn --utt2spk=ark:data/train/split15/1/utt2spk scp:data/train/split15/1/cmvn.scp scp:data/train/split15/1/feats.scp ark:- | add-deltas ark:- ark:- |' - 
apply-cmvn --utt2spk=ark:data/train/split15/1/utt2spk scp:data/train/split15/1/cmvn.scp scp:data/train/split15/1/feats.scp ark:- 
WARNING (apply-cmvn[5.5.266~1-77ac7]:ReadScriptFile():kaldi-table.cc:34) Error opening script file: data/train/split15/1/cmvn.scp
ERROR (apply-cmvn[5.5.266~1-77ac7]:RandomAccessTableReader():util/kaldi-table-inl.h:2512) Error opening RandomAccessTableReader object  (rspecifier is: scp:data/train/split15/1/cmvn.scp)

[ Stack-Trace: ]
kaldi::MessageLogger::LogMessage() const
kaldi::MessageLogger::LogAndThrow::operator=(kaldi::MessageLogger const&)
kaldi::RandomAccessTableReader<kaldi::KaldiObjectHolder<kaldi::Matrix<double> > >::RandomAccessTableReader(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
kaldi::RandomAccessTableReaderMapped<kaldi::KaldiObjectHolder<kaldi::Matrix<double> > >::RandomAccessTableReaderMapped(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
main
__libc_start_main
_start

kaldi::KaldiFatalErroradd-deltas ark:- ark:- 
ERROR (feat-to-dim[5.5.266~1-77ac7]:main():feat-to-dim.cc:58) Could not read any features (empty archive?)

[ Stack-Trace: ]
kaldi::MessageLogger::LogMessage() const
kaldi::MessageLogger::LogAndThrow::operator=(kaldi::MessageLogger const&)
main
__libc_start_main
_start

kaldi::KaldiFatalErrorerror getting feature dimension

**Comment by veenveenveen** [comment]
@KiAlexander Before you run this script , you should run DNN_train.sh first to generate language model (sirlm tool to generate the language model).In order to run successfully，you have to check the audio file path and then modify it to your own path on your computer, I refer to this project, you can have a look. -> https://github.com/KunalDhawan/ASR-System-for-Hindi-Language, and this -> https://goo.gl/eQZkMP
